LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
ENTITY mux21 IS
	PORT(
		w0,w1:IN STD_LOGIC;
		s: IN STD_LOGIC;
		y: OUT STD_LOGIC
		);
END ENTITY mux21;
ARCHITECTURE mux21A OF mux21 IS
	BEGIN
		PROCESS(w0,w1,s)
			BEGIN
				IF s ='0' THEN
					y<=w0;
						ELSE
					y<=w1;
				END IF;
		END PROCESS;
END ARCHITECTURE mux21A;
